import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import "keen-slider/keen-slider.min.css";
import Footer from "@/components/layout/Footer";
import { readSingleton } from "@directus/sdk";
import directus from "@/lib/directus";
import { TSettings } from "@/interfaces";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/components/ReduxProvider";
import ThemeWrapper from "@/components/layout/ThemeWrapper";
import FaviconSwitcher from "@/components/layout/FaviconSwitcher";
import MobileCartSidebar from "@/components/pages/cart/MobileCartSidebar";
import StatusBarControl from "@/components/common/StatusBarControl";
import BackButtonHandler from "@/components/BackButtonHandler";
import TopLoader from "@/components/layout/TopLoader";
import PlatformNavbar from "@/components/layout/PlatformNavbar";
import AppInit from "@/components/AppInt";
import NoticeBar from "@/components/layout/header/NoticeBar";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"], // optional: add other weights if needed
  display: "swap",
});

export const metadata: Metadata = {
  title: "Radical Engineering",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = (await directus.request(
    readSingleton("settings")
  )) as TSettings;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
      (function () {
        const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        const isNative = /android|iphone|ipad/.test(navigator.userAgent.toLowerCase());
        const storedTheme = localStorage.getItem('theme');
        const theme = isNative
          ? (prefersDark ? 'dark' : 'light')
          : (storedTheme || (prefersDark ? 'dark' : 'light'));
        document.documentElement.classList.add(theme);
      })();
    `,
          }}
        />
      </head>
      <body className={`${lato.variable} antialiased `}>
        <ReduxProvider>
          <NoticeBar />
          <FaviconSwitcher />
          <ThemeWrapper>
            <AppInit />
            <StatusBarControl />
            <TopLoader />
            <Toaster position="top-right" />
            {<PlatformNavbar settings={settings} />}
            <main className="min-h-[80vh] relative dark:bg-darkBG ">
              {children}
            </main>
            <MobileCartSidebar />
            <Footer settings={settings} />
            <BackButtonHandler />
          </ThemeWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
