import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import "keen-slider/keen-slider.min.css";
import Footer from "@/components/layout/Footer";
import { readSingleton } from "@directus/sdk";
import directus from "@/lib/directus";
import { TSettings } from "@/interfaces";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/components/ReduxProvider";

import ThemeWrapper from "@/components/layout/ThemeWrapper";
import FaviconSwitcher from "@/components/layout/FaviconSwitcher";
import MobileCartSidebar from "@/components/pages/cart/MobileCartSidebar";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"], // optional: add other weights if needed
  display: "swap",
});

export const metadata: Metadata = {
  title: "Radical Engineering",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = (await directus.request(
    readSingleton("settings")
  )) as TSettings;

  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased `}>
        <ReduxProvider>
          <FaviconSwitcher />
          <ThemeWrapper>
            <Toaster position="bottom-right" />
            <Navbar settings={settings} />
            <main className="min-h-[80vh] relative dark:bg-darkBG ">
              {children}
            </main>
            <MobileCartSidebar />
            <Footer />
          </ThemeWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
