import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import "keen-slider/keen-slider.min.css";
import Footer from "@/components/layout/Footer";
import { readSingleton } from "@directus/sdk";
import directus from "@/lib/directus";
import { TSettings } from "@/interfaces";

import ReduxProvider from "@/components/ReduxProvider";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"], // optional: add other weights if needed
});

export const metadata: Metadata = {
  title: "Radical Engineering",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = (await directus.request(
    readSingleton("settings")
  )) as TSettings;

  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        <ReduxProvider>
          <Navbar settings={settings} />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
