name: Deploy Radical Engineering Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 22
            cd /var/www/radicalengineering.com.bd/html
            git pull https://shanto902:${{ secrets.GIT_TOKEN }}@github.com/shanto902/radical-engineering.git main

            npm install
            npm run build
            pm2 reload frontend-radical-engineering || pm2 start npm --name "frontend-radical-engineering" -- start
            pm2 save
            pm2 startup --silent
